### ISSUE TITLE
Problem with compiling 

### ISSUE THREAD

**Issue by SnailMail57** [interkosmos/fortran-raylib#1]
I wanted to do the test program but when I went to compile it, it said 

       use :: raylib

raylib.mod could not be opened.

it wasn’t able to find it. This is what I used to compile: $ gfortran -L/wesley/local/lib -I/wesley/raylib/build/raylib/include -o example example.f90 \libfortran-raylib.a -lraylib -lGL -lpthread -lm  -ldl -lrt -1X11

I’m not sure it I need to rewrite wesley/local/lib if it’s that which is messing it up. Other than that no other errors.

**Comment by interkosmos** [comment]
When linking Fortran modules, the compiler must be able to find the corresponding `*.mod` files (additionally to the object files). You have to point the include search directory (compiler flag `-I`) to the directory of `raylib.mod`, `raylib_camera.mod`, `raylib_math.mod`, and `raylib_util.mod`. For example, just make sure that path `/wesley/raylib/build/raylib/include` exists and the module file are placed in there.

**Comment by SnailMail57** [comment]
I Found where the mod files really are now I have this


Gfortran -L/wesley/local/lib -I/home/wesley/raylib/build/fortran-raylib -o example example.f90 \ libfortran-raylib.a -lGL -lpthread -ldl -lrt -lX11

It fixed the previous error but now

 It gave me the error 

/usr/bin/ld: cannot find -lraylib: no such file or directory

And 

/usr/bin/ld: cannot find -libfortran-raylib.a: no such file or directory

Thank you for helping

**Comment by SnailMail57** [comment]
I just tried to make the examples with

$make examples

Nonexistent include directory ./include/ [Wmissing-include-dirs]

**Comment by interkosmos** [comment]
Either link against the static library `libraylib.a` or the shared library `libraylib.so`. For the static one, add the path to the library; for the shared one, link with `-lraylib`. You may have to set the library search path through compiler flag `-L`.

Replace `-libfortran-raylib.a` with the path to the library (remove the `-`).

You can ignore the warning regarding the missing include directory.

**Comment by SnailMail57** [comment]
Thank you so much for you help so far i'll test out what you said in a bit.

But from what you were saying I need to do this?

Gfortran -L/wesley/local/lib -I/home/wesley/raylib/build/fortran-raylib -o example example.f90 \ /home/wesley/raylib/build/fortran-raylib(replaced libfortran-raylib.a) -lraylib(added this to link) -lGL -lpthread -ldl -lrt -lX11

**Comment by SnailMail57** [comment]
I'm sorry but could you give an example of what I would write with what you just said.

**Comment by interkosmos** [comment]
If you have a shared library `libraylib.so`:

```
$ gfortran -L/path/to/raylib -o example example.f90 \
  libfortran-raylib.a -lraylib -lGL -lpthread -lm
```

Or, to link the static library `libraylib.a`:

```
$ gfortran -o example example.f90 libfortran-raylib.a \
  /path/to/libraylib.a -lGL -lpthread -lm
```

It‘s probably easier to put `libraylib.a`, `libfortran-raylib.a`, and all module files in the workspace directory of your project.

**Comment by SnailMail57** [comment]
Should fortran-raylib be in /build or /build/raylib/fortran-raylib

**Comment by interkosmos** [comment]
Well, it‘s up to you and how you prefer your build environment. Put everything in one directory, or set the absolute/relative paths when compiling. Just make sure the compiler finds all required libraries and module files.

**Comment by SnailMail57** [comment]
I deleted raylib and reinstalled it as well as Fortan-raylib.

I made it a static version of raylib and didn't make a build file but used make in its src file. Then installed fortran-raylib. After marking an example.f90 and put in the original compile Line the only error it gave me was path error. 

I then tired your static compile line in your last message and it gave me the same problem. It still doesn't work but better than before. It just doesn't see the librarylib.a

**Comment by interkosmos** [comment]
I cannot reproduce your described issues. Just compile raylib to the static library `libraylib.a`, and copy the file into your *fortran-raylib* directory. Then, run:

```
$ make RAYLIB=libraylib.a
$ make examples RAYLIB=libraylib.a
```

Instead of `libraylib.a`, you can alternatively set the absolute or relative path to the static raylib library.

Let’s say your project workspace directory contains the following files:

* `example.f90`
* `raylib.mod`
* `raylib_camera.mod`
* `raylib_math.mod`
* `raylib_util.mod`
* `libfortran-raylib.a`
* `libraylib.a`

You can then just run:

```
$ gfortran -o example example.f90 libfortran-raylib.a libraylib.a -lGL -lpthread -lm
```
